// Code generated by ent, DO NOT EDIT.

package thesis

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the thesis type in the database.
	Label = "thesis"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTime holds the string denoting the time field in the database.
	FieldTime = "time"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgeUploaders holds the string denoting the uploaders edge name in mutations.
	EdgeUploaders = "uploaders"
	// Table holds the table name of the thesis in the database.
	Table = "theses"
	// UploadersTable is the table that holds the uploaders relation/edge.
	UploadersTable = "theses"
	// UploadersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UploadersInverseTable = "users"
	// UploadersColumn is the table column denoting the uploaders relation/edge.
	UploadersColumn = "user_files"
)

// Columns holds all SQL columns for thesis fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldTime,
	FieldURL,
	FieldType,
	FieldStatus,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "theses"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_files",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTime holds the default value on creation for the "time" field.
	DefaultTime func() time.Time
)

// OrderOption defines the ordering options for the Thesis queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByTime orders the results by the time field.
func ByTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTime, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByUploadersField orders the results by uploaders field.
func ByUploadersField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUploadersStep(), sql.OrderByField(field, opts...))
	}
}
func newUploadersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UploadersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UploadersTable, UploadersColumn),
	)
}
