// Code generated by ent, DO NOT EDIT.

package thesis

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ZEQUANR/zhulong/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Thesis {
	return predicate.Thesis(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Thesis {
	return predicate.Thesis(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Thesis {
	return predicate.Thesis(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Thesis {
	return predicate.Thesis(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Thesis {
	return predicate.Thesis(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Thesis {
	return predicate.Thesis(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Thesis {
	return predicate.Thesis(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Thesis {
	return predicate.Thesis(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Thesis {
	return predicate.Thesis(sql.FieldLTE(FieldID, id))
}

// FileName applies equality check predicate on the "file_name" field. It's identical to FileNameEQ.
func FileName(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldEQ(FieldFileName, v))
}

// FileURL applies equality check predicate on the "file_url" field. It's identical to FileURLEQ.
func FileURL(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldEQ(FieldFileURL, v))
}

// FileState applies equality check predicate on the "file_state" field. It's identical to FileStateEQ.
func FileState(v int) predicate.Thesis {
	return predicate.Thesis(sql.FieldEQ(FieldFileState, v))
}

// UploadTime applies equality check predicate on the "upload_time" field. It's identical to UploadTimeEQ.
func UploadTime(v time.Time) predicate.Thesis {
	return predicate.Thesis(sql.FieldEQ(FieldUploadTime, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Thesis {
	return predicate.Thesis(sql.FieldEQ(FieldCreateTime, v))
}

// ThesisTitle applies equality check predicate on the "thesis_title" field. It's identical to ThesisTitleEQ.
func ThesisTitle(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldEQ(FieldThesisTitle, v))
}

// FileNameEQ applies the EQ predicate on the "file_name" field.
func FileNameEQ(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldEQ(FieldFileName, v))
}

// FileNameNEQ applies the NEQ predicate on the "file_name" field.
func FileNameNEQ(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldNEQ(FieldFileName, v))
}

// FileNameIn applies the In predicate on the "file_name" field.
func FileNameIn(vs ...string) predicate.Thesis {
	return predicate.Thesis(sql.FieldIn(FieldFileName, vs...))
}

// FileNameNotIn applies the NotIn predicate on the "file_name" field.
func FileNameNotIn(vs ...string) predicate.Thesis {
	return predicate.Thesis(sql.FieldNotIn(FieldFileName, vs...))
}

// FileNameGT applies the GT predicate on the "file_name" field.
func FileNameGT(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldGT(FieldFileName, v))
}

// FileNameGTE applies the GTE predicate on the "file_name" field.
func FileNameGTE(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldGTE(FieldFileName, v))
}

// FileNameLT applies the LT predicate on the "file_name" field.
func FileNameLT(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldLT(FieldFileName, v))
}

// FileNameLTE applies the LTE predicate on the "file_name" field.
func FileNameLTE(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldLTE(FieldFileName, v))
}

// FileNameContains applies the Contains predicate on the "file_name" field.
func FileNameContains(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldContains(FieldFileName, v))
}

// FileNameHasPrefix applies the HasPrefix predicate on the "file_name" field.
func FileNameHasPrefix(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldHasPrefix(FieldFileName, v))
}

// FileNameHasSuffix applies the HasSuffix predicate on the "file_name" field.
func FileNameHasSuffix(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldHasSuffix(FieldFileName, v))
}

// FileNameIsNil applies the IsNil predicate on the "file_name" field.
func FileNameIsNil() predicate.Thesis {
	return predicate.Thesis(sql.FieldIsNull(FieldFileName))
}

// FileNameNotNil applies the NotNil predicate on the "file_name" field.
func FileNameNotNil() predicate.Thesis {
	return predicate.Thesis(sql.FieldNotNull(FieldFileName))
}

// FileNameEqualFold applies the EqualFold predicate on the "file_name" field.
func FileNameEqualFold(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldEqualFold(FieldFileName, v))
}

// FileNameContainsFold applies the ContainsFold predicate on the "file_name" field.
func FileNameContainsFold(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldContainsFold(FieldFileName, v))
}

// FileURLEQ applies the EQ predicate on the "file_url" field.
func FileURLEQ(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldEQ(FieldFileURL, v))
}

// FileURLNEQ applies the NEQ predicate on the "file_url" field.
func FileURLNEQ(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldNEQ(FieldFileURL, v))
}

// FileURLIn applies the In predicate on the "file_url" field.
func FileURLIn(vs ...string) predicate.Thesis {
	return predicate.Thesis(sql.FieldIn(FieldFileURL, vs...))
}

// FileURLNotIn applies the NotIn predicate on the "file_url" field.
func FileURLNotIn(vs ...string) predicate.Thesis {
	return predicate.Thesis(sql.FieldNotIn(FieldFileURL, vs...))
}

// FileURLGT applies the GT predicate on the "file_url" field.
func FileURLGT(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldGT(FieldFileURL, v))
}

// FileURLGTE applies the GTE predicate on the "file_url" field.
func FileURLGTE(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldGTE(FieldFileURL, v))
}

// FileURLLT applies the LT predicate on the "file_url" field.
func FileURLLT(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldLT(FieldFileURL, v))
}

// FileURLLTE applies the LTE predicate on the "file_url" field.
func FileURLLTE(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldLTE(FieldFileURL, v))
}

// FileURLContains applies the Contains predicate on the "file_url" field.
func FileURLContains(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldContains(FieldFileURL, v))
}

// FileURLHasPrefix applies the HasPrefix predicate on the "file_url" field.
func FileURLHasPrefix(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldHasPrefix(FieldFileURL, v))
}

// FileURLHasSuffix applies the HasSuffix predicate on the "file_url" field.
func FileURLHasSuffix(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldHasSuffix(FieldFileURL, v))
}

// FileURLIsNil applies the IsNil predicate on the "file_url" field.
func FileURLIsNil() predicate.Thesis {
	return predicate.Thesis(sql.FieldIsNull(FieldFileURL))
}

// FileURLNotNil applies the NotNil predicate on the "file_url" field.
func FileURLNotNil() predicate.Thesis {
	return predicate.Thesis(sql.FieldNotNull(FieldFileURL))
}

// FileURLEqualFold applies the EqualFold predicate on the "file_url" field.
func FileURLEqualFold(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldEqualFold(FieldFileURL, v))
}

// FileURLContainsFold applies the ContainsFold predicate on the "file_url" field.
func FileURLContainsFold(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldContainsFold(FieldFileURL, v))
}

// FileStateEQ applies the EQ predicate on the "file_state" field.
func FileStateEQ(v int) predicate.Thesis {
	return predicate.Thesis(sql.FieldEQ(FieldFileState, v))
}

// FileStateNEQ applies the NEQ predicate on the "file_state" field.
func FileStateNEQ(v int) predicate.Thesis {
	return predicate.Thesis(sql.FieldNEQ(FieldFileState, v))
}

// FileStateIn applies the In predicate on the "file_state" field.
func FileStateIn(vs ...int) predicate.Thesis {
	return predicate.Thesis(sql.FieldIn(FieldFileState, vs...))
}

// FileStateNotIn applies the NotIn predicate on the "file_state" field.
func FileStateNotIn(vs ...int) predicate.Thesis {
	return predicate.Thesis(sql.FieldNotIn(FieldFileState, vs...))
}

// FileStateGT applies the GT predicate on the "file_state" field.
func FileStateGT(v int) predicate.Thesis {
	return predicate.Thesis(sql.FieldGT(FieldFileState, v))
}

// FileStateGTE applies the GTE predicate on the "file_state" field.
func FileStateGTE(v int) predicate.Thesis {
	return predicate.Thesis(sql.FieldGTE(FieldFileState, v))
}

// FileStateLT applies the LT predicate on the "file_state" field.
func FileStateLT(v int) predicate.Thesis {
	return predicate.Thesis(sql.FieldLT(FieldFileState, v))
}

// FileStateLTE applies the LTE predicate on the "file_state" field.
func FileStateLTE(v int) predicate.Thesis {
	return predicate.Thesis(sql.FieldLTE(FieldFileState, v))
}

// FileStateIsNil applies the IsNil predicate on the "file_state" field.
func FileStateIsNil() predicate.Thesis {
	return predicate.Thesis(sql.FieldIsNull(FieldFileState))
}

// FileStateNotNil applies the NotNil predicate on the "file_state" field.
func FileStateNotNil() predicate.Thesis {
	return predicate.Thesis(sql.FieldNotNull(FieldFileState))
}

// UploadTimeEQ applies the EQ predicate on the "upload_time" field.
func UploadTimeEQ(v time.Time) predicate.Thesis {
	return predicate.Thesis(sql.FieldEQ(FieldUploadTime, v))
}

// UploadTimeNEQ applies the NEQ predicate on the "upload_time" field.
func UploadTimeNEQ(v time.Time) predicate.Thesis {
	return predicate.Thesis(sql.FieldNEQ(FieldUploadTime, v))
}

// UploadTimeIn applies the In predicate on the "upload_time" field.
func UploadTimeIn(vs ...time.Time) predicate.Thesis {
	return predicate.Thesis(sql.FieldIn(FieldUploadTime, vs...))
}

// UploadTimeNotIn applies the NotIn predicate on the "upload_time" field.
func UploadTimeNotIn(vs ...time.Time) predicate.Thesis {
	return predicate.Thesis(sql.FieldNotIn(FieldUploadTime, vs...))
}

// UploadTimeGT applies the GT predicate on the "upload_time" field.
func UploadTimeGT(v time.Time) predicate.Thesis {
	return predicate.Thesis(sql.FieldGT(FieldUploadTime, v))
}

// UploadTimeGTE applies the GTE predicate on the "upload_time" field.
func UploadTimeGTE(v time.Time) predicate.Thesis {
	return predicate.Thesis(sql.FieldGTE(FieldUploadTime, v))
}

// UploadTimeLT applies the LT predicate on the "upload_time" field.
func UploadTimeLT(v time.Time) predicate.Thesis {
	return predicate.Thesis(sql.FieldLT(FieldUploadTime, v))
}

// UploadTimeLTE applies the LTE predicate on the "upload_time" field.
func UploadTimeLTE(v time.Time) predicate.Thesis {
	return predicate.Thesis(sql.FieldLTE(FieldUploadTime, v))
}

// UploadTimeIsNil applies the IsNil predicate on the "upload_time" field.
func UploadTimeIsNil() predicate.Thesis {
	return predicate.Thesis(sql.FieldIsNull(FieldUploadTime))
}

// UploadTimeNotNil applies the NotNil predicate on the "upload_time" field.
func UploadTimeNotNil() predicate.Thesis {
	return predicate.Thesis(sql.FieldNotNull(FieldUploadTime))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Thesis {
	return predicate.Thesis(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Thesis {
	return predicate.Thesis(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Thesis {
	return predicate.Thesis(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Thesis {
	return predicate.Thesis(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Thesis {
	return predicate.Thesis(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Thesis {
	return predicate.Thesis(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Thesis {
	return predicate.Thesis(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Thesis {
	return predicate.Thesis(sql.FieldLTE(FieldCreateTime, v))
}

// ThesisTitleEQ applies the EQ predicate on the "thesis_title" field.
func ThesisTitleEQ(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldEQ(FieldThesisTitle, v))
}

// ThesisTitleNEQ applies the NEQ predicate on the "thesis_title" field.
func ThesisTitleNEQ(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldNEQ(FieldThesisTitle, v))
}

// ThesisTitleIn applies the In predicate on the "thesis_title" field.
func ThesisTitleIn(vs ...string) predicate.Thesis {
	return predicate.Thesis(sql.FieldIn(FieldThesisTitle, vs...))
}

// ThesisTitleNotIn applies the NotIn predicate on the "thesis_title" field.
func ThesisTitleNotIn(vs ...string) predicate.Thesis {
	return predicate.Thesis(sql.FieldNotIn(FieldThesisTitle, vs...))
}

// ThesisTitleGT applies the GT predicate on the "thesis_title" field.
func ThesisTitleGT(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldGT(FieldThesisTitle, v))
}

// ThesisTitleGTE applies the GTE predicate on the "thesis_title" field.
func ThesisTitleGTE(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldGTE(FieldThesisTitle, v))
}

// ThesisTitleLT applies the LT predicate on the "thesis_title" field.
func ThesisTitleLT(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldLT(FieldThesisTitle, v))
}

// ThesisTitleLTE applies the LTE predicate on the "thesis_title" field.
func ThesisTitleLTE(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldLTE(FieldThesisTitle, v))
}

// ThesisTitleContains applies the Contains predicate on the "thesis_title" field.
func ThesisTitleContains(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldContains(FieldThesisTitle, v))
}

// ThesisTitleHasPrefix applies the HasPrefix predicate on the "thesis_title" field.
func ThesisTitleHasPrefix(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldHasPrefix(FieldThesisTitle, v))
}

// ThesisTitleHasSuffix applies the HasSuffix predicate on the "thesis_title" field.
func ThesisTitleHasSuffix(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldHasSuffix(FieldThesisTitle, v))
}

// ThesisTitleEqualFold applies the EqualFold predicate on the "thesis_title" field.
func ThesisTitleEqualFold(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldEqualFold(FieldThesisTitle, v))
}

// ThesisTitleContainsFold applies the ContainsFold predicate on the "thesis_title" field.
func ThesisTitleContainsFold(v string) predicate.Thesis {
	return predicate.Thesis(sql.FieldContainsFold(FieldThesisTitle, v))
}

// HasUploaders applies the HasEdge predicate on the "uploaders" edge.
func HasUploaders() predicate.Thesis {
	return predicate.Thesis(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UploadersTable, UploadersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUploadersWith applies the HasEdge predicate on the "uploaders" edge with a given conditions (other predicates).
func HasUploadersWith(preds ...predicate.User) predicate.Thesis {
	return predicate.Thesis(func(s *sql.Selector) {
		step := newUploadersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Thesis) predicate.Thesis {
	return predicate.Thesis(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Thesis) predicate.Thesis {
	return predicate.Thesis(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Thesis) predicate.Thesis {
	return predicate.Thesis(sql.NotPredicates(p))
}
