// Code generated by ent, DO NOT EDIT.

package students

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the students type in the database.
	Label = "students"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCollege holds the string denoting the college field in the database.
	FieldCollege = "college"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldClass holds the string denoting the class field in the database.
	FieldClass = "class"
	// FieldIdentity holds the string denoting the identity field in the database.
	FieldIdentity = "identity"
	// Table holds the table name of the students in the database.
	Table = "students"
)

// Columns holds all SQL columns for students fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCollege,
	FieldPhone,
	FieldSubject,
	FieldClass,
	FieldIdentity,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Students queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCollege orders the results by the college field.
func ByCollege(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollege, opts...).ToFunc()
}

// ByPhone orders the results by the phone field.
func ByPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhone, opts...).ToFunc()
}

// BySubject orders the results by the subject field.
func BySubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubject, opts...).ToFunc()
}

// ByClass orders the results by the class field.
func ByClass(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClass, opts...).ToFunc()
}

// ByIdentity orders the results by the identity field.
func ByIdentity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdentity, opts...).ToFunc()
}
