// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ZEQUANR/zhulong/ent/students"
	"github.com/ZEQUANR/zhulong/ent/user"
)

// StudentsCreate is the builder for creating a Students entity.
type StudentsCreate struct {
	config
	mutation *StudentsMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (sc *StudentsCreate) SetName(s string) *StudentsCreate {
	sc.mutation.SetName(s)
	return sc
}

// SetCollege sets the "college" field.
func (sc *StudentsCreate) SetCollege(s string) *StudentsCreate {
	sc.mutation.SetCollege(s)
	return sc
}

// SetPhone sets the "phone" field.
func (sc *StudentsCreate) SetPhone(s string) *StudentsCreate {
	sc.mutation.SetPhone(s)
	return sc
}

// SetSubject sets the "subject" field.
func (sc *StudentsCreate) SetSubject(s string) *StudentsCreate {
	sc.mutation.SetSubject(s)
	return sc
}

// SetClass sets the "class" field.
func (sc *StudentsCreate) SetClass(s string) *StudentsCreate {
	sc.mutation.SetClass(s)
	return sc
}

// SetIdentity sets the "identity" field.
func (sc *StudentsCreate) SetIdentity(s string) *StudentsCreate {
	sc.mutation.SetIdentity(s)
	return sc
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (sc *StudentsCreate) SetUsersID(id int) *StudentsCreate {
	sc.mutation.SetUsersID(id)
	return sc
}

// SetUsers sets the "users" edge to the User entity.
func (sc *StudentsCreate) SetUsers(u *User) *StudentsCreate {
	return sc.SetUsersID(u.ID)
}

// Mutation returns the StudentsMutation object of the builder.
func (sc *StudentsCreate) Mutation() *StudentsMutation {
	return sc.mutation
}

// Save creates the Students in the database.
func (sc *StudentsCreate) Save(ctx context.Context) (*Students, error) {
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *StudentsCreate) SaveX(ctx context.Context) *Students {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *StudentsCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *StudentsCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *StudentsCreate) check() error {
	if _, ok := sc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Students.name"`)}
	}
	if _, ok := sc.mutation.College(); !ok {
		return &ValidationError{Name: "college", err: errors.New(`ent: missing required field "Students.college"`)}
	}
	if _, ok := sc.mutation.Phone(); !ok {
		return &ValidationError{Name: "phone", err: errors.New(`ent: missing required field "Students.phone"`)}
	}
	if _, ok := sc.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "Students.subject"`)}
	}
	if _, ok := sc.mutation.Class(); !ok {
		return &ValidationError{Name: "class", err: errors.New(`ent: missing required field "Students.class"`)}
	}
	if _, ok := sc.mutation.Identity(); !ok {
		return &ValidationError{Name: "identity", err: errors.New(`ent: missing required field "Students.identity"`)}
	}
	if _, ok := sc.mutation.UsersID(); !ok {
		return &ValidationError{Name: "users", err: errors.New(`ent: missing required edge "Students.users"`)}
	}
	return nil
}

func (sc *StudentsCreate) sqlSave(ctx context.Context) (*Students, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *StudentsCreate) createSpec() (*Students, *sqlgraph.CreateSpec) {
	var (
		_node = &Students{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(students.Table, sqlgraph.NewFieldSpec(students.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.Name(); ok {
		_spec.SetField(students.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := sc.mutation.College(); ok {
		_spec.SetField(students.FieldCollege, field.TypeString, value)
		_node.College = value
	}
	if value, ok := sc.mutation.Phone(); ok {
		_spec.SetField(students.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := sc.mutation.Subject(); ok {
		_spec.SetField(students.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := sc.mutation.Class(); ok {
		_spec.SetField(students.FieldClass, field.TypeString, value)
		_node.Class = value
	}
	if value, ok := sc.mutation.Identity(); ok {
		_spec.SetField(students.FieldIdentity, field.TypeString, value)
		_node.Identity = value
	}
	if nodes := sc.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   students.UsersTable,
			Columns: []string{students.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_students = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StudentsCreateBulk is the builder for creating many Students entities in bulk.
type StudentsCreateBulk struct {
	config
	err      error
	builders []*StudentsCreate
}

// Save creates the Students entities in the database.
func (scb *StudentsCreateBulk) Save(ctx context.Context) ([]*Students, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Students, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StudentsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *StudentsCreateBulk) SaveX(ctx context.Context) []*Students {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *StudentsCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *StudentsCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
