// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ZEQUANR/zhulong/ent/teachers"
)

// TeachersCreate is the builder for creating a Teachers entity.
type TeachersCreate struct {
	config
	mutation *TeachersMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (tc *TeachersCreate) SetName(s string) *TeachersCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetCollege sets the "college" field.
func (tc *TeachersCreate) SetCollege(s string) *TeachersCreate {
	tc.mutation.SetCollege(s)
	return tc
}

// SetPhone sets the "phone" field.
func (tc *TeachersCreate) SetPhone(s string) *TeachersCreate {
	tc.mutation.SetPhone(s)
	return tc
}

// SetIdentity sets the "identity" field.
func (tc *TeachersCreate) SetIdentity(s string) *TeachersCreate {
	tc.mutation.SetIdentity(s)
	return tc
}

// Mutation returns the TeachersMutation object of the builder.
func (tc *TeachersCreate) Mutation() *TeachersMutation {
	return tc.mutation
}

// Save creates the Teachers in the database.
func (tc *TeachersCreate) Save(ctx context.Context) (*Teachers, error) {
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TeachersCreate) SaveX(ctx context.Context) *Teachers {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TeachersCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TeachersCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TeachersCreate) check() error {
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Teachers.name"`)}
	}
	if _, ok := tc.mutation.College(); !ok {
		return &ValidationError{Name: "college", err: errors.New(`ent: missing required field "Teachers.college"`)}
	}
	if _, ok := tc.mutation.Phone(); !ok {
		return &ValidationError{Name: "phone", err: errors.New(`ent: missing required field "Teachers.phone"`)}
	}
	if _, ok := tc.mutation.Identity(); !ok {
		return &ValidationError{Name: "identity", err: errors.New(`ent: missing required field "Teachers.identity"`)}
	}
	return nil
}

func (tc *TeachersCreate) sqlSave(ctx context.Context) (*Teachers, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TeachersCreate) createSpec() (*Teachers, *sqlgraph.CreateSpec) {
	var (
		_node = &Teachers{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(teachers.Table, sqlgraph.NewFieldSpec(teachers.FieldID, field.TypeInt))
	)
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(teachers.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.College(); ok {
		_spec.SetField(teachers.FieldCollege, field.TypeString, value)
		_node.College = value
	}
	if value, ok := tc.mutation.Phone(); ok {
		_spec.SetField(teachers.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := tc.mutation.Identity(); ok {
		_spec.SetField(teachers.FieldIdentity, field.TypeString, value)
		_node.Identity = value
	}
	return _node, _spec
}

// TeachersCreateBulk is the builder for creating many Teachers entities in bulk.
type TeachersCreateBulk struct {
	config
	err      error
	builders []*TeachersCreate
}

// Save creates the Teachers entities in the database.
func (tcb *TeachersCreateBulk) Save(ctx context.Context) ([]*Teachers, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Teachers, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeachersMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TeachersCreateBulk) SaveX(ctx context.Context) []*Teachers {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TeachersCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TeachersCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
