// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ZEQUANR/zhulong/ent/predicate"
	"github.com/ZEQUANR/zhulong/ent/thesis"
	"github.com/ZEQUANR/zhulong/ent/user"
)

// ThesisUpdate is the builder for updating Thesis entities.
type ThesisUpdate struct {
	config
	hooks    []Hook
	mutation *ThesisMutation
}

// Where appends a list predicates to the ThesisUpdate builder.
func (tu *ThesisUpdate) Where(ps ...predicate.Thesis) *ThesisUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetName sets the "name" field.
func (tu *ThesisUpdate) SetName(s string) *ThesisUpdate {
	tu.mutation.SetName(s)
	return tu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tu *ThesisUpdate) SetNillableName(s *string) *ThesisUpdate {
	if s != nil {
		tu.SetName(*s)
	}
	return tu
}

// SetTime sets the "time" field.
func (tu *ThesisUpdate) SetTime(t time.Time) *ThesisUpdate {
	tu.mutation.SetTime(t)
	return tu
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (tu *ThesisUpdate) SetNillableTime(t *time.Time) *ThesisUpdate {
	if t != nil {
		tu.SetTime(*t)
	}
	return tu
}

// SetURL sets the "url" field.
func (tu *ThesisUpdate) SetURL(s string) *ThesisUpdate {
	tu.mutation.SetURL(s)
	return tu
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (tu *ThesisUpdate) SetNillableURL(s *string) *ThesisUpdate {
	if s != nil {
		tu.SetURL(*s)
	}
	return tu
}

// SetType sets the "type" field.
func (tu *ThesisUpdate) SetType(i int) *ThesisUpdate {
	tu.mutation.ResetType()
	tu.mutation.SetType(i)
	return tu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tu *ThesisUpdate) SetNillableType(i *int) *ThesisUpdate {
	if i != nil {
		tu.SetType(*i)
	}
	return tu
}

// AddType adds i to the "type" field.
func (tu *ThesisUpdate) AddType(i int) *ThesisUpdate {
	tu.mutation.AddType(i)
	return tu
}

// SetStatus sets the "status" field.
func (tu *ThesisUpdate) SetStatus(i int) *ThesisUpdate {
	tu.mutation.ResetStatus()
	tu.mutation.SetStatus(i)
	return tu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tu *ThesisUpdate) SetNillableStatus(i *int) *ThesisUpdate {
	if i != nil {
		tu.SetStatus(*i)
	}
	return tu
}

// AddStatus adds i to the "status" field.
func (tu *ThesisUpdate) AddStatus(i int) *ThesisUpdate {
	tu.mutation.AddStatus(i)
	return tu
}

// SetUploadersID sets the "uploaders" edge to the User entity by ID.
func (tu *ThesisUpdate) SetUploadersID(id int) *ThesisUpdate {
	tu.mutation.SetUploadersID(id)
	return tu
}

// SetNillableUploadersID sets the "uploaders" edge to the User entity by ID if the given value is not nil.
func (tu *ThesisUpdate) SetNillableUploadersID(id *int) *ThesisUpdate {
	if id != nil {
		tu = tu.SetUploadersID(*id)
	}
	return tu
}

// SetUploaders sets the "uploaders" edge to the User entity.
func (tu *ThesisUpdate) SetUploaders(u *User) *ThesisUpdate {
	return tu.SetUploadersID(u.ID)
}

// Mutation returns the ThesisMutation object of the builder.
func (tu *ThesisUpdate) Mutation() *ThesisMutation {
	return tu.mutation
}

// ClearUploaders clears the "uploaders" edge to the User entity.
func (tu *ThesisUpdate) ClearUploaders() *ThesisUpdate {
	tu.mutation.ClearUploaders()
	return tu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *ThesisUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *ThesisUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *ThesisUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *ThesisUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *ThesisUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(thesis.Table, thesis.Columns, sqlgraph.NewFieldSpec(thesis.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Name(); ok {
		_spec.SetField(thesis.FieldName, field.TypeString, value)
	}
	if value, ok := tu.mutation.Time(); ok {
		_spec.SetField(thesis.FieldTime, field.TypeTime, value)
	}
	if value, ok := tu.mutation.URL(); ok {
		_spec.SetField(thesis.FieldURL, field.TypeString, value)
	}
	if value, ok := tu.mutation.GetType(); ok {
		_spec.SetField(thesis.FieldType, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedType(); ok {
		_spec.AddField(thesis.FieldType, field.TypeInt, value)
	}
	if value, ok := tu.mutation.Status(); ok {
		_spec.SetField(thesis.FieldStatus, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedStatus(); ok {
		_spec.AddField(thesis.FieldStatus, field.TypeInt, value)
	}
	if tu.mutation.UploadersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thesis.UploadersTable,
			Columns: []string{thesis.UploadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.UploadersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thesis.UploadersTable,
			Columns: []string{thesis.UploadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{thesis.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// ThesisUpdateOne is the builder for updating a single Thesis entity.
type ThesisUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ThesisMutation
}

// SetName sets the "name" field.
func (tuo *ThesisUpdateOne) SetName(s string) *ThesisUpdateOne {
	tuo.mutation.SetName(s)
	return tuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tuo *ThesisUpdateOne) SetNillableName(s *string) *ThesisUpdateOne {
	if s != nil {
		tuo.SetName(*s)
	}
	return tuo
}

// SetTime sets the "time" field.
func (tuo *ThesisUpdateOne) SetTime(t time.Time) *ThesisUpdateOne {
	tuo.mutation.SetTime(t)
	return tuo
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (tuo *ThesisUpdateOne) SetNillableTime(t *time.Time) *ThesisUpdateOne {
	if t != nil {
		tuo.SetTime(*t)
	}
	return tuo
}

// SetURL sets the "url" field.
func (tuo *ThesisUpdateOne) SetURL(s string) *ThesisUpdateOne {
	tuo.mutation.SetURL(s)
	return tuo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (tuo *ThesisUpdateOne) SetNillableURL(s *string) *ThesisUpdateOne {
	if s != nil {
		tuo.SetURL(*s)
	}
	return tuo
}

// SetType sets the "type" field.
func (tuo *ThesisUpdateOne) SetType(i int) *ThesisUpdateOne {
	tuo.mutation.ResetType()
	tuo.mutation.SetType(i)
	return tuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tuo *ThesisUpdateOne) SetNillableType(i *int) *ThesisUpdateOne {
	if i != nil {
		tuo.SetType(*i)
	}
	return tuo
}

// AddType adds i to the "type" field.
func (tuo *ThesisUpdateOne) AddType(i int) *ThesisUpdateOne {
	tuo.mutation.AddType(i)
	return tuo
}

// SetStatus sets the "status" field.
func (tuo *ThesisUpdateOne) SetStatus(i int) *ThesisUpdateOne {
	tuo.mutation.ResetStatus()
	tuo.mutation.SetStatus(i)
	return tuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tuo *ThesisUpdateOne) SetNillableStatus(i *int) *ThesisUpdateOne {
	if i != nil {
		tuo.SetStatus(*i)
	}
	return tuo
}

// AddStatus adds i to the "status" field.
func (tuo *ThesisUpdateOne) AddStatus(i int) *ThesisUpdateOne {
	tuo.mutation.AddStatus(i)
	return tuo
}

// SetUploadersID sets the "uploaders" edge to the User entity by ID.
func (tuo *ThesisUpdateOne) SetUploadersID(id int) *ThesisUpdateOne {
	tuo.mutation.SetUploadersID(id)
	return tuo
}

// SetNillableUploadersID sets the "uploaders" edge to the User entity by ID if the given value is not nil.
func (tuo *ThesisUpdateOne) SetNillableUploadersID(id *int) *ThesisUpdateOne {
	if id != nil {
		tuo = tuo.SetUploadersID(*id)
	}
	return tuo
}

// SetUploaders sets the "uploaders" edge to the User entity.
func (tuo *ThesisUpdateOne) SetUploaders(u *User) *ThesisUpdateOne {
	return tuo.SetUploadersID(u.ID)
}

// Mutation returns the ThesisMutation object of the builder.
func (tuo *ThesisUpdateOne) Mutation() *ThesisMutation {
	return tuo.mutation
}

// ClearUploaders clears the "uploaders" edge to the User entity.
func (tuo *ThesisUpdateOne) ClearUploaders() *ThesisUpdateOne {
	tuo.mutation.ClearUploaders()
	return tuo
}

// Where appends a list predicates to the ThesisUpdate builder.
func (tuo *ThesisUpdateOne) Where(ps ...predicate.Thesis) *ThesisUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *ThesisUpdateOne) Select(field string, fields ...string) *ThesisUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Thesis entity.
func (tuo *ThesisUpdateOne) Save(ctx context.Context) (*Thesis, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *ThesisUpdateOne) SaveX(ctx context.Context) *Thesis {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *ThesisUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *ThesisUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *ThesisUpdateOne) sqlSave(ctx context.Context) (_node *Thesis, err error) {
	_spec := sqlgraph.NewUpdateSpec(thesis.Table, thesis.Columns, sqlgraph.NewFieldSpec(thesis.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Thesis.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, thesis.FieldID)
		for _, f := range fields {
			if !thesis.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != thesis.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Name(); ok {
		_spec.SetField(thesis.FieldName, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Time(); ok {
		_spec.SetField(thesis.FieldTime, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.URL(); ok {
		_spec.SetField(thesis.FieldURL, field.TypeString, value)
	}
	if value, ok := tuo.mutation.GetType(); ok {
		_spec.SetField(thesis.FieldType, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedType(); ok {
		_spec.AddField(thesis.FieldType, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.Status(); ok {
		_spec.SetField(thesis.FieldStatus, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedStatus(); ok {
		_spec.AddField(thesis.FieldStatus, field.TypeInt, value)
	}
	if tuo.mutation.UploadersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thesis.UploadersTable,
			Columns: []string{thesis.UploadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.UploadersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thesis.UploadersTable,
			Columns: []string{thesis.UploadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Thesis{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{thesis.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
