// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ZEQUANR/zhulong/ent/thesis"
	"github.com/ZEQUANR/zhulong/ent/user"
)

// ThesisCreate is the builder for creating a Thesis entity.
type ThesisCreate struct {
	config
	mutation *ThesisMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (tc *ThesisCreate) SetName(s string) *ThesisCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetTime sets the "time" field.
func (tc *ThesisCreate) SetTime(t time.Time) *ThesisCreate {
	tc.mutation.SetTime(t)
	return tc
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (tc *ThesisCreate) SetNillableTime(t *time.Time) *ThesisCreate {
	if t != nil {
		tc.SetTime(*t)
	}
	return tc
}

// SetURL sets the "url" field.
func (tc *ThesisCreate) SetURL(s string) *ThesisCreate {
	tc.mutation.SetURL(s)
	return tc
}

// SetType sets the "type" field.
func (tc *ThesisCreate) SetType(i int) *ThesisCreate {
	tc.mutation.SetType(i)
	return tc
}

// SetStatus sets the "status" field.
func (tc *ThesisCreate) SetStatus(i int) *ThesisCreate {
	tc.mutation.SetStatus(i)
	return tc
}

// SetUploadersID sets the "uploaders" edge to the User entity by ID.
func (tc *ThesisCreate) SetUploadersID(id int) *ThesisCreate {
	tc.mutation.SetUploadersID(id)
	return tc
}

// SetNillableUploadersID sets the "uploaders" edge to the User entity by ID if the given value is not nil.
func (tc *ThesisCreate) SetNillableUploadersID(id *int) *ThesisCreate {
	if id != nil {
		tc = tc.SetUploadersID(*id)
	}
	return tc
}

// SetUploaders sets the "uploaders" edge to the User entity.
func (tc *ThesisCreate) SetUploaders(u *User) *ThesisCreate {
	return tc.SetUploadersID(u.ID)
}

// Mutation returns the ThesisMutation object of the builder.
func (tc *ThesisCreate) Mutation() *ThesisMutation {
	return tc.mutation
}

// Save creates the Thesis in the database.
func (tc *ThesisCreate) Save(ctx context.Context) (*Thesis, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *ThesisCreate) SaveX(ctx context.Context) *Thesis {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *ThesisCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *ThesisCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *ThesisCreate) defaults() {
	if _, ok := tc.mutation.Time(); !ok {
		v := thesis.DefaultTime()
		tc.mutation.SetTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *ThesisCreate) check() error {
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Thesis.name"`)}
	}
	if _, ok := tc.mutation.Time(); !ok {
		return &ValidationError{Name: "time", err: errors.New(`ent: missing required field "Thesis.time"`)}
	}
	if _, ok := tc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Thesis.url"`)}
	}
	if _, ok := tc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Thesis.type"`)}
	}
	if _, ok := tc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Thesis.status"`)}
	}
	return nil
}

func (tc *ThesisCreate) sqlSave(ctx context.Context) (*Thesis, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *ThesisCreate) createSpec() (*Thesis, *sqlgraph.CreateSpec) {
	var (
		_node = &Thesis{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(thesis.Table, sqlgraph.NewFieldSpec(thesis.FieldID, field.TypeInt))
	)
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(thesis.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.Time(); ok {
		_spec.SetField(thesis.FieldTime, field.TypeTime, value)
		_node.Time = value
	}
	if value, ok := tc.mutation.URL(); ok {
		_spec.SetField(thesis.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := tc.mutation.GetType(); ok {
		_spec.SetField(thesis.FieldType, field.TypeInt, value)
		_node.Type = value
	}
	if value, ok := tc.mutation.Status(); ok {
		_spec.SetField(thesis.FieldStatus, field.TypeInt, value)
		_node.Status = value
	}
	if nodes := tc.mutation.UploadersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thesis.UploadersTable,
			Columns: []string{thesis.UploadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_files = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ThesisCreateBulk is the builder for creating many Thesis entities in bulk.
type ThesisCreateBulk struct {
	config
	err      error
	builders []*ThesisCreate
}

// Save creates the Thesis entities in the database.
func (tcb *ThesisCreateBulk) Save(ctx context.Context) ([]*Thesis, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Thesis, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ThesisMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *ThesisCreateBulk) SaveX(ctx context.Context) []*Thesis {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *ThesisCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *ThesisCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
